apps/metro/urls.py
from django.urls import path
from django.conf import settings
from apps.metro.views import index, rota
from django.conf.urls.static import static

app_name = 'metro'
urlpatterns = [
    path('', index, name="index"),
    path('rota/<int:estacao_origem>/<int:estacao_destino>/', rota, name='rota'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

infometro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.metro.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/metro/models.py
from django.db import models
import networkx as nx
import matplotlib.pyplot as plt
from colorfield.fields import ColorField

class Linha(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    cor = ColorField(default='#FF0000')
    ordem = models.PositiveIntegerField(default=0,blank=False,null=False)

    class Meta:
        ordering = ['ordem']

    def __str__(self) -> str:
        return self.nome
    
class Estacao(models.Model):
    nome = models.CharField(max_length=100)
    linha = models.ForeignKey("Linha", on_delete=models.CASCADE)
    conexoes = models.ManyToManyField('self', blank=True)
    ordem = models.PositiveIntegerField(default=0,blank=False,null=False)

    class Meta:
        ordering = ['ordem']
        verbose_name = 'estação'
        verbose_name_plural = "estações"
        unique_together = ('nome', 'linha',)

    def __str__(self):
        return f'{self.nome} ({self.linha})'
    
    @staticmethod
    def desenhar_grafo():
        G = nx.DiGraph()

        # Adicionando conexões
        estacoes = Estacao.objects.all()
        for estacao in estacoes:
            for conexao in estacao.conexoes.all():
                peso = 1 if estacao.linha == conexao.linha else 2 # 2: Baldeação
                G.add_edge(estacao, conexao, weight=peso)

        pos = nx.spectral_layout(G)
        nx.draw_networkx_nodes(G, pos, node_size=500, node_color='skyblue')
        nx.draw_networkx_edges(G, pos, edgelist=G.edges(), edge_color='gray')
        edge_labels = {(u, v): G[u][v]['weight'] for u, v in G.edges()}
        nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color='black')
        node_labels = {node: f'{node.nome} ({node.linha})' for node in G.nodes()}
        nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=10)

        plt.axis('off')
        plt.show()

class Destino(models.Model):
    nome = models.CharField(max_length=100)
    origem = models.ForeignKey("Estacao", on_delete=models.CASCADE, related_name="estacao_origem")
    destino = models.ForeignKey("Estacao", on_delete=models.CASCADE, related_name="estacao_destino")
    ordem = models.PositiveIntegerField(default=0,blank=False,null=False)
    
    class Meta:
        ordering = ['ordem']

    def __str__(self) -> str:
        return f'{self.nome} ({self.origem.nome}-{self.destino.nome})'

class Rota():
    @staticmethod
    def mais_curta(origem, destino):
        if origem == destino:
            return None
        origem = Estacao.objects.get(pk=origem)
        destino = Estacao.objects.get(pk=destino)
        if origem.nome == destino.nome:
            return None
        
        G = nx.DiGraph()

        # Adicionando conexões
        estacoes = Estacao.objects.all().order_by('ordem')
        for estacao in estacoes:
            for conexao in estacao.conexoes.all():
                peso = 1 if estacao.linha == conexao.linha else 5 # 5: Baldeação
                G.add_edge(estacao, conexao, weight=peso)

        # Encontrando o caminho mais curto usando o algoritmo de Dijkstra
        try:
            caminho = nx.shortest_path(G, source=origem, target=destino, weight='weight')
            return caminho
        except nx.NetworkXNoPath:
            return None
        
    @staticmethod
    def separa_rota_por_destino(rota):
        bandeja = []
        rota_por_destino = []
        destino_escolhido = ''
        pontuacao = 0

        dict_destinos = {}
        destinos = Destino.objects.all().order_by('ordem')
        for destino in destinos:
            rota_destino = Rota.mais_curta(destino.origem.id, destino.destino.id)
            dict_destinos[f'{destino.id}/{destino.nome}'] = rota_destino

        for estacao in rota:
            bandeja.append(estacao)
            encontrou = False
            for chave, valor in dict_destinos.items():
                for i in range(len(valor) - len(bandeja) + 1):
                    if valor[i:i+len(bandeja)] == bandeja:
                        encontrou = True
                        pos_apos_barra = chave.index('/') + 1
                        if len(bandeja) == pontuacao:
                            destino_escolhido = destino_escolhido + '/' + chave[pos_apos_barra:] if destino_escolhido != chave[pos_apos_barra:] else chave[pos_apos_barra:]
                        else:
                            destino_escolhido = chave[pos_apos_barra:]
                            pontuacao = len(bandeja)
            pontuacao = 0
            if not encontrou:
                if bandeja[-2].linha != bandeja[-1].linha:
                    ultima_estacao = bandeja.pop()
                    bandeja.insert(0, destino_escolhido) if len(bandeja) > 1 else None
                    rota_por_destino.append(bandeja)
                    bandeja = []
                    bandeja.append(ultima_estacao)
                    continue
                ultimas_duas_estacoes = bandeja[-2:]
                bandeja.pop()
                bandeja.insert(0, destino_escolhido) if len(bandeja) > 1 else None
                rota_por_destino.append(bandeja)
                bandeja = ultimas_duas_estacoes
        if encontrou:
            bandeja.insert(0, destino_escolhido)
            rota_por_destino.append(bandeja)

        return rota_por_destino
    
    @staticmethod
    def instrucoes(iteravel):
        rota = Rota.separa_rota_por_destino(iteravel)
        instrucoes = []
        # 0 = Apenas passando pela estação, já embarcado. [0, <estacao>]
        # 1 = Embarque na estação. [1, <estacao>, <destino>]
        # 2 = Desembarque na estação. [2, <estacao>]
        # 3 = Transferência de linha. [3, <estacao_origem>, <estacao_destino>]
        for i, trecho in enumerate(rota):
            if len(trecho) == 1:
                instrucoes.append([3, trecho[0], rota[i + 1][1]])
                continue
            for ii, valor in enumerate(trecho):
                if ii == 0:
                    destino = valor
                    continue
                if 'ultima_estacao' in locals() and ultima_estacao.linha != valor.linha:
                    instrucoes.append([3, ultima_estacao, valor])
                if ii == 1:
                    instrucoes.append([1, valor, destino])
                elif ii == len(trecho) - 1:
                    instrucoes.append([2, valor])
                else:
                    instrucoes.append([0, valor])
                ultima_estacao = valor
        return instrucoes

apps/metro/views.py
from django.shortcuts import render
from .models import Estacao, Rota

def index(request):
    estacoes = Estacao.objects.all().order_by('linha', 'ordem')
    return render(request, 'index.html', {'estacoes': estacoes})

def rota(request, estacao_origem, estacao_destino):
    instrucoes = Rota.instrucoes(Rota.mais_curta(estacao_origem, estacao_destino))
    return render(request, 'rota.html', {'instrucoes': instrucoes})

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rotas - Metrô do Recife</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div id="main" class="col-lg-10 col-md-10 col-sm-10">
        <form action="{% url 'metro:index' %}">
            <select name="origem" id="origem" class="origem form-control">
                <option value="" disabled selected>Selecione ORIGEM</option>{% for estacao in estacoes %}{% ifchanged estacao.linha %}{% if not forloop.first %}
                </optgroup>{% endif %}
                <optgroup label="{{estacao.linha}}">{% endifchanged %}
                    <option value="{{estacao.id}}">{{estacao.nome}}</option>{% if forloop.last %}
                </optgroup>{% endif %}{% endfor %}
            </select>
            <div id="bloco-destino">
                <div class="vline"></div>
                <select name="destino" id="destino" class="destino form-control">
                    <option value="" disabled selected>Selecione DESTINO</option>{% for estacao in estacoes %}{% ifchanged estacao.linha %}{% if not forloop.first %}
                    </optgroup>{% endif %}
                    <optgroup label="{{estacao.linha}}">{% endifchanged %}
                        <option value="{{estacao.id}}">{{estacao.nome}}</option>{% if forloop.last %}
                    </optgroup>{% endif %}{% endfor %}
                </select>
            </div>            
        </form>
        <div id="loading" class="lds-ellipsis">
            <div></div><div></div><div></div><div></div>
        </div>
    </div>
    <script src="{% static 'js/init.js' %}"></script>
</body>
</html>

templates/rota.html
{% for instrucao in instrucoes %}{% if instrucao.0 == 0 %}
<div class="instrucao transito">
    <div class="dot"></div>
    {{instrucao.1.nome}}
</div>{% endif %}{% if instrucao.0 == 1 %}
<div class="instrucao embarque" style="background-color: {{instrucao.1.linha.cor}}">
    Embarque na estação <strong>{{instrucao.1.nome}}</strong> (destino: <strong>{{instrucao.2}}</strong>)
</div>{% endif %}{% if instrucao.0 == 2 %}
<div class="instrucao desembarque" style="background-color: {{instrucao.1.linha.cor}}">
    Desembarque na estação <strong>{{instrucao.1.nome}}</strong>
</div>{% endif %}{% if instrucao.0 == 3 %}
<div class="instrucao transferencia" style="background: linear-gradient(135deg, {{instrucao.1.linha.cor}} 50%, {{instrucao.2.linha.cor}} 50%)">
    Faça a transferência da linha <strong>{{instrucao.1.linha}}</strong> para a linha <strong>{{instrucao.2.linha}}</strong>
</div>{% endif %}{% endfor %}
<a href="{% url 'metro:index' %}"><button type="button" class="btn btn-secondary btn-sm container-fluid nova-rota">Nova Rota</button></a>